name: Run Oasis Bot Automatically

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Jalankan setiap hari pada pukul 00:00 UTC

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install

    - name: Run Main Script
      run: node main.js

