name: Run Oasis Bot Automatically

on:
  push:
    branches:
      - main  # Workflow akan dijalankan setiap kali ada perubahan di branch 'main'

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install

    - name: Run Setup
      run: npm run setup

    - name: Run Bot
      run: npm run start

